### ISSUE TITLE
so slow training

### ISSUE THREAD

**Issue by nightfuryyy** [faustomorales/keras-ocr#102]
i train on 1 gpu v100 
batchsize = 16
len(images_train) = 80k
time train per epoch = 7h 
is it normal ?
Thank you so much for awesome repo.

**Comment by faustomorales** [comment]
That does not sound normal. Are you sure the GPU is getting used? Please verify using `tf.config.list_physical_devices()`.

**Comment by nightfuryyy** [comment]
print(keras_ocr.__version__)
print(tf.__version__)
print("Num GPUs Available: ", tf.config.experimental.list_physical_devices())
-> 
0.6.3
2.0.0
Num GPUs Available:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'), PhysicalDevice(name='/physical_device:GPU:
0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'), PhysicalDevice(name='/physical_device:XL
A_GPU:1', device_type='XLA_GPU')]
i tried retrainning on 2 gpu, but only 1 gpu is used and it's still slow.
