### ISSUE TITLE
ValueError : Too many values to unpack ( OpenCV issue )

### ISSUE THREAD

**Issue by ashishanand7** [faustomorales/keras-ocr#11]
The error is related to OpenCV findContours meethod call.

My Env:

Python : 3.6..4
OpenCV: 3.4.2.16

Code to reproduce:

```
image = keras_ocr.tools.read('X00016469612.jpg')

# Predictions is a list of (text, box) tuples.
predictions = pipeline.recognize(image=image)
```

Error:

ValueError: too many values to unpack (expected 2)

Points to _getBoxes_ method:

`contours, _ = cv2.findContours(segmap.astype('uint8'),mode=cv2.RETR_TREE,    method=cv2.CHAIN_APPROX_SIMPLE)`

Solution:
 
findContours returns 3 values. Changing the above line to below should fix it.

`__ , contours , __ = cv2.findContours(segmap.astype('uint8'),mode=cv2.RETR_TREE,    method=cv2.CHAIN_APPROX_SIMPLE)`

**Comment by faustomorales** [comment]
Thanks for raising this! OpenCV 2 and OpenCV 4 return three values. Only OpenCV 3 returns two. So the current behavior works for older and newer versions than that which you are on. We only ever use the `contours` so I've just pushed c2fe60a3ae5ff600a4a6370ea66f64501bd47d74 which uses `cv2.findContours()[-2]`. By asking for the second to last value, we will always get the contours, regardless of OpenCV version. Of course, this assumes they don't change it again in OpenCV 5. Let me know if this doesn't resolve your issue.

**Comment by ashishanand7** [comment]
Hi 

As mentioned above , I am on OpenCV  3 only , ( v3.4.2.16) . It also returns 3 values.
Yes the latest commit fixes it. 
Thanks for this wonderful repo.

**Comment by faustomorales** [comment]
Oops! I meant to say that OpenCV 2 and 4 return two values while OpenCV 3
returns three. I got it mixed up when typing up my previous comment.

For future folks stumbling on to this issue, there are more details in this
SO question:
https://stackoverflow.com/questions/20851365/opencv-contours-need-more-than-2-values-to-unpack

Glad the last commit resolves the issue. Happy OCRing!
