### ISSUE TITLE
Special characters not detected !

### ISSUE THREAD

**Issue by GhadaJouini** [faustomorales/keras-ocr#118]
Hey ! 
Thanks @faustomorales  for this amazing work.
I'm trying to extract any kind of text scene in any images (test this code on driving license data and identity cards).
for the alphabits it works fine but the special characters like "/" in the date it's  detected  as number "1" I guess cause we didn't train the model on such data. My question is how can I re-train this model for another data (like identity cards in my case ..) can you guide me how to do this  on google colab.
hope you could help me and thanks again 👍

**Comment by faustomorales** [comment]
Hi! The pre-trained recognizer does not include punctuation. Please see the recognizer portions of the [end-to-end example](https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html) for a demonstration on how to use your own alphabet and generate synthetic data for it.

I'm closing this issue for now because this is neither a bug nor a proposed enhancement.

**Comment by GhadaJouini** [comment]
Hi, faustomorales, 
I tried to retrain the detection and recognition model to detect the special characters and I followed the implementation explained in https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html but unfortunately, the detection part is lost and I can't understand why because I took the same weights as before ( craft_mlt_25.h5, crnn_kurapan.h5)
these are some samples of the output:

![Capture1](https://user-images.githubusercontent.com/32711189/93869049-366a9b80-fcc3-11ea-9c30-7171b02f73ad.PNG)
![Capture2](https://user-images.githubusercontent.com/32711189/93869051-379bc880-fcc3-11ea-95c3-eaa307d02dec.PNG)

I'm using this project to extract information from driving licenses this is the before and after 

![withoud end to end pretraining](https://user-images.githubusercontent.com/32711189/93869747-24d5c380-fcc4-11ea-905d-651b08211852.PNG)
![end to end training result](https://user-images.githubusercontent.com/32711189/93869752-27381d80-fcc4-11ea-8ace-5b82940290bf.PNG)

I hope you can guide me throw this and I'll be so grateful thanks alot again :)
