### ISSUE TITLE
AssertionError: Error occurred verifying sha256.

### ISSUE THREAD

**Issue by vishnukv64** [faustomorales/keras-ocr#121]
After installing via pip and i tried running this piece of code 
pipeline = keras_ocr.pipeline.Pipeline()

it throws an sha256 error
![Screenshot from 2020-09-10 01-42-24](https://user-images.githubusercontent.com/33051467/92648468-12907880-f307-11ea-9ffd-0e678d398c45.png)

Any thoughts?

**Comment by cmdlinebeep** [comment]
@vishnukv64   What was the solution?  I just ran into this too trying to follow along the Notebook.

**Comment by vishnukv64** [comment]
> @vishnukv64   What was the solution?  I just ran into this too trying to follow along the Notebook.  

I still didn't solve this !! There is another thread open for this issue

I kinda did a temporary fix by directly downloading the weights to ./keras-ocr location and it runs

Will need to check for future updates for this fix

**Comment by cmdlinebeep** [comment]
Thanks vishnukv64, I did search for other issues but apparently missed it.  :-) 
https://github.com/faustomorales/keras-ocr/issues/117
