### ISSUE TITLE
Minor type errors in code for section "Use the model for inference"

### ISSUE THREAD

**Issue by OoiSC** [faustomorales/keras-ocr#13]
Perhaps these two lines from the section "Use the model for inference"
pipeline = keras_ocr.pipelines.Pipeline(detector=detector, recognizer=recognizer)
image, text, lines = next(image_generators[0])

should be
pipeline = keras_ocr.pipeline.Pipeline(detector=detector, recognizer=recognizer)
image, lines = next(image_generators[0])

**Comment by faustomorales** [comment]
Thanks for catching! I fixed that along with the two related subsequent lines as part of 441be2304e1bbf59ab491ec5330e589f6453f8b1 just now.

**Comment by faustomorales** [comment]
Closing since I think this has been addressed. Let me know if I'm mistaken. Thanks!
