### ISSUE TITLE
Multi gpu Training

### ISSUE THREAD

**Issue by bayethiernodiop** [faustomorales/keras-ocr#14]
Hello, how would someone use multiple gpus to train, since with tf2 the recomended way is using tf.distribute.Strategy but this suppose you do the model definition and compilation in the strategy context, do we still use multi_gpu_model from keras on the recognizer.training_model for example : recognizer.training_model = multi_gpu_model(recognizer.training_model, gpus=4)

**Comment by lmolhw5252** [comment]
hello, did you solve it?
