### ISSUE TITLE
Documentation about 'end-to-end' training is misleading 

### ISSUE THREAD

**Issue by lambdaofgod** [faustomorales/keras-ocr#143]
The [example](https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html) of model training in documentation is misleading, as it's not actually end-to-end - it trains detector and recognizer separately.

The example actually shows training of **all parts** of pipeline. The process isn't end-to-end though.

**Comment by faustomorales** [comment]
Thanks for raising this. I agree that the typical use of the term "end-to-end" in deep learning doesn't apply here and that the current wording is misleading. Would you be willing to file a PR to fix/change it?
