### ISSUE TITLE
Upload models again (error 404)

### ISSUE THREAD

**Issue by ivsanro1** [faustomorales/keras-ocr#144]
Seems like the default mediafire URLs for the pretrained models are down. Could you upload them somewhere else and update the code? Thank you

**Comment by ivsanro1** [comment]
I just saw that the problem is up to 0.8.4, since from 0.8.5, the link points to a github URL which works. I suggest removing prior versions from pypi due to deprecation.

**Comment by faustomorales** [comment]
Thanks for raising this! I've yanked all package versions before v0.8.5.  The versions will still be available but installation will trigger the message: "The URLs for weights have changed. Please upgrade."
