### ISSUE TITLE
pypi repository for keras-ocr has unknown license type

### ISSUE THREAD

**Issue by simon-fleishman** [faustomorales/keras-ocr#170]
Our company opensource scanner returns unknown license for pypi repo for keras-ocr
Artifact:                    PYPI - keras-ocr==0.8.6
  Licenses: (1)
    License:
      Name:         UNKNOWN
      Commercial:   false

Could anyone please advise?

**Comment by faustomorales** [comment]
This repository is provided under the [MIT license](https://github.com/faustomorales/keras-ocr/blob/master/LICENSE). The metadata on PyPi has been updated.
