### ISSUE TITLE
error terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by AlexBlack2202** [faustomorales/keras-ocr#2]
i use your demo code, and my app was crash. It show

> 2019-11-19 16:05:38.112665: W tensorflow/core/framework/allocator.cc:107] Allocation of 3121348608 exceeds 10% of system memory.
> 2019-11-19 16:05:40.014946: W tensorflow/core/framework/allocator.cc:107] Allocation of 3121348608 exceeds 10% of system memory.
> 2019-11-19 16:05:40.014951: W tensorflow/core/framework/allocator.cc:107] Allocation of 3121348608 exceeds 10% of system memory.
> 2019-11-19 16:05:45.262924: W tensorflow/core/framework/allocator.cc:107] Allocation of 3121348608 exceeds 10% of system memory.
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc

I do not have GPU, my memory is 32GB.
the code i use

```
import matplotlib.pyplot as plt

import keras_ocr

detector = keras_ocr.detection.Detector(pretrained=True)
image = keras_ocr.tools.read('tests/test_image.jpg')

boxes = detector.detect(images=[image])[0]
canvas = keras_ocr.detection.drawBoxes(image, boxes)
plt.imshow(canvas)
```

How can i run this?

**Comment by faustomorales** [comment]
Hello! Could you provide a few more details to help me reproduce?

- TensorFlow version (`import tensorflow as tf; tf.__version__`)
- Keras version (`import keras; keras.__version__`)
- Did you try to run the demo code more than once with the same result?
- Was any other code executed before the demo code?

**Comment by AlexBlack2202** [comment]
Hi faustomorales, some detail of my system is:

TensorFlow version: 1.14.0.
Keras version: 2.3.1

"Did you try to run the demo code more than once with the same result" yes, I run it more than 5 times, and  totally crash.

"Was any other code executed before the demo code?" No, I just create a new test.py file and paste your example code.

It is show error after run this line "boxes = detector.detect(images=[image])[0]", the memory increase very fast (from 4GB to 11GB in 2-3 second), and crash.
 log in terminal:

>  terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted

Thank you.

**Comment by faustomorales** [comment]
I ran the demo code with that combination and was unable to reproduce. Some more things to check --

1. What version of OpenCV do you have (`import cv2; cv2.__version__`)
2. Could you verify that `image.shape` is `(480, 640, 3)`? I'm wondering if the package is reading the file incorrectly somehow.
3. You could try running the demo code with TensorFlow 2.0.0 by doing `pip uninstall -y tensorflow` then `pip install tensorflow==2.0.0`.

Thank you for your patience!

**Comment by AlexBlack2202** [comment]
Hi faustomorales, thank you for fast reply,

my image size is (3024, 4032, 3). I forget to resize it into (480, 640, 3).

When i resize to (480, 640, 3), it work.

Thank you very much.

**Comment by faustomorales** [comment]
Glad that worked out for you! Just to clarify, you don't *have* to use (480, 640) exactly. The model should still work for different dimensions / aspect ratios.
