### ISSUE TITLE
Using trained model for predictions

### ISSUE THREAD

**Issue by MounaBC** [faustomorales/keras-ocr#21]
Once we've finished a training and generated the .h5 file, how do we create a new detector (or recognizer) object that will use that model and the new calculated weights?

**Comment by faustomorales** [comment]
You can reload the trained models using `detector.model.load_weights("path/to/detector/weights.h5")` and `recognizer.model.load_weights("path/to/recognizer/weights.h5")`.

I think this fully answers your question so I am closing this issue -- but if I've misunderstood please comment back here and I can re-open. Thanks!

**Comment by andriykutsevol** [comment]
I got the .h5 files as described in the documentation:
https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html

--------

Then I'm trying to load them:

detector = keras_ocr.detection.Detector()
detector.model.load_weights("./keras_ocr/data/detector.h5")

recognizer = keras_ocr.recognition.Recognizer()
recognizer.model.load_weights("./keras_ocr/data/recognizer.h5")

pipeline = keras_ocr.pipeline.Pipeline(detector=detector, recognizer=recognizer)

--------

And I get the next error:

ValueError: Cannot assign value to variable ' fc_12/kernel:0': Shape mismatch.The variable shape (256, 37), and the assigned value shape (256, 41) are incompatible.
