### ISSUE TITLE
use recognizer on multiple images

### ISSUE THREAD

**Issue by bayethiernodiop** [faustomorales/keras-ocr#23]
Hello, it would be very useful to be able to use just the recognizer on multiple images like when using the pipeline.
the use case: I use YOLO to extract and crop some text area I am interested in and i want to predict the texts using just the recognizer.
Any suggestions or guides?
Thanks.

**Comment by wetgi** [comment]
Hello, that should be possible.

`recognizer = keras_ocr.recognition.Recognizer(....)
recognizer.compile()
predicted = recognizer.recognize(image)
`
there is also the method `recognize_from_boxes(self, images, box_groups, **kwargs)`
box_groups could be your input from YOLO.

**Comment by bayethiernodiop** [comment]
@wetgi I know about the first method, but I have to loop to call it on many images it takes only one image, also the last one supposes that you have a text detector outputting bounding boxes, but here just suppose I have many cropped images in a folder.

**Comment by faustomorales** [comment]
I can think of two ways to do this:

## Option 1
Use `recognize_from_boxes()` as suggested by @wetgi and supply a `box_groups` argument that specifies the box as being the full image. I haven't tested this but hopefully it explains the idea. Assume that `images` is a list of filepaths to cropped, single-word boxes and `recognizer` is a `keras_ocr.recognition.Recognizer` instance.

```python
def make_box(image):
    return np.array([
        [0, 0],
        [image.shape[1], 0],
        [image.shape[1], image.shape[0]],
        [0, image.shape[0]]
    ])

images = [keras_ocr.tools.read(image) for image in images]
box_groups = [[make_box(image)] for image in images]
predictions = [
    g[0] for g in recognizer.recognize_from_boxes(images=images, box_groups=box_groups)
]
```

We could also amend the implementation of `recognize_from_boxes` to allow users to omit the `box_groups` argument to get the same behavior.

## Option 2
You could subclass `keras_ocr.detection.Detector` and implement the requisite `detector.detect` method using your YOLO model. It needs to do is return `box_groups`. This would enable you to do the whole process in one pass and use the batching logic provided by `keras_ocr.pipeline.Pipeline`.

Hope this helps!

**Comment by faustomorales** [comment]
Closing this issue for now as it appears that there are at least two ways to achieve the desired result. Please comment back if I'm mistaken and we can reopen. Thanks!

**Comment by bayethiernodiop** [comment]
Thanks for your responses, I think it would be cool to be able to use a flag to indicate to recognize from images without giving the box_groups as suggested.
