### ISSUE TITLE
Jupyter notebook crashing

### ISSUE THREAD

**Issue by semaraugusto** [faustomorales/keras-ocr#29]
Whenever the Pipeline function is activated in two different kernels, one of them crashes.

Reproducible exemple:
```
import keras_ocr

pipeline = keras_ocr.pipeline.Pipeline()
```
Try adding this cell to 2 different kernels and run them.

**Comment by bayethiernodiop** [comment]
Did you check if you have enough memory? For example if you using GPU TF by default, allocate all the GPU memory.

**Comment by faustomorales** [comment]
I have been unable to reproduce this issue on MacOS with a local notebook server or in a Docker container. Please provide more details on reproducing the issue and a stack trace or log.

**Comment by faustomorales** [comment]
Closed due to lack of reproducibility. We can re-open if more details become available.
