### ISSUE TITLE
How to load the recognition model after training?

### ISSUE THREAD

**Issue by Zepharchit** [faustomorales/keras-ocr#33]
Hi, I am having the issue of loading the model after training the recogniser. 
![Screenshot from 2020-02-26 12-42-34](https://user-images.githubusercontent.com/51807559/75320863-9ae08c00-5895-11ea-91a0-3ce29a99cb5e.png)
![Screenshot from 2020-02-26 12-42-56](https://user-images.githubusercontent.com/51807559/75320867-9e741300-5895-11ea-9742-a5cf269c5b0d.png)

**Comment by bayethiernodiop** [comment]
can you show load_model code ?

**Comment by Zepharchit** [comment]
Its for loading the recognition model only
![Screenshot from 2020-02-26 13-31-54](https://user-images.githubusercontent.com/51807559/75324187-68865d00-589c-11ea-8ed4-70f7c0e2290e.png)

**Comment by bayethiernodiop** [comment]
I see, the way i use to load my recognizer after training is : 
`recognizer = keras_ocr.recognition.Recognizer(alphabet=alphabet) # I give the alphabet so that it doesn't load the default weights

recognizer.model.load_weights("./recognizer_2020-01-23T12:25:22.160959.h5")
`

**Comment by Zepharchit** [comment]
Thanks for helping out with this approach.
