### ISSUE TITLE
Use trained model

### ISSUE THREAD

**Issue by tfilip** [faustomorales/keras-ocr#35]
Hello!

Is there any way to pass the model trained to the recognizer? I haven't found anything in the documentation.

**Comment by faustomorales** [comment]
Hi @tfilip! You can load a set of weights that you trained using `recognizer.model.load_weights('path/to/weights.h5')`. There was an example for how to load weights for the detector but not the recognizer, so I pushed ad016cee4e95e661a5b87bf68d885a79ba85e5b1 to fix it. Thanks for the feedback.

I'm going to close this for now but please let me know if this does not resolve the issue and we can re-open.
