### ISSUE TITLE
text detector - weights and test with efficientnet

### ISSUE THREAD

**Issue by anas-899** [faustomorales/keras-ocr#36]
Thanks for the amazing work.

did you try craft text-detector with efficientnet?
I saw you have implemented the detection part with two backbones (vgg) and (efficientnet)

but the part of calling the efficientnet and weights are not provided
is there any plan to include it in future?

**Comment by faustomorales** [comment]
Hi there! Yes, I am experimenting with this but I'm still tuning the training process to achieve results comparable to the VGG weights that currently ship with the package. I don't have a ton of time to work on that piece of it these days but hope to return to it sometime in 2020.

**Comment by raghavgurbaxani** [comment]
Hi @faustomorales 

Thank you for your amazing work. Is there a way to change the basenet in the detector ? as you know vgg backbone is very compute heavy. I'd like to train my own model with efficientnet or resnet. 

How do I go about it ?
