### ISSUE TITLE
End to end training tensorflow.python.framework.errors_impl.ResourceExhaustedError

### ISSUE THREAD

**Issue by OoiSC** [faustomorales/keras-ocr#4]
I encountered following error when I ran end to end training code. 
File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[1,64,160,160] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node model_1/upconv3.conv.3/Conv2D (defined at train2.py:140) ]]

Train2.py contains a slightly modified version of your end to end training software. I had to modify your code to suit my Windows environment e.g. Windows file names cannot contain characters like colon and to support re-run.

Error occurs at following line:

detector.model.fit_generator(
    generator=detection_train_generator,
    steps_per_epoch=math.ceil(len(background_splits[0]) / detector_batch_size),
    epochs=1000,
    workers=0,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(restore_best_weights=True, patience=5),
        tf.keras.callbacks.CSVLogger(f'{detector_basepath}.csv'),
        tf.keras.callbacks.ModelCheckpoint(filepath=f'{detector_basepath}.h5')
    ],
    validation_data=detection_val_generator,
    validation_steps=math.ceil(len(background_splits[1]) / detector_batch_size)
)

I have attached the file containing the source code below.
[train2py.pdf](https://github.com/faustomorales/keras-ocr/files/4018391/train2py.pdf)

I have also attached all of the messages displayed at the Windows command line when I ran 
python train2.py.

[log1.log](https://github.com/faustomorales/keras-ocr/files/4018393/log1.log)

I have also attached the ouput of my pip list so that you can see what python modules and versions that I have installed.

[pip-list.txt](https://github.com/faustomorales/keras-ocr/files/4018395/pip-list.txt)

My gpu is just a Nvidia GeForce MX150 with 4GB RAM. My PC has 16GB RAM.

**Comment by faustomorales** [comment]
Thanks for raising this. I think 4GB is not enough GPU memory to train this model, especially if it's also being used to drive the display. Most common computer vision deep learning models require > 8GB of memory. It's possible that we could use a smaller backbone for the detector but it still might not work with a 4GB GPU. So, in this case, I'm afraid this is a hardware limitation. You could use Google Colab to get a free >12GB GPU. It might be larger if you get a P100 instead of a K80.

**Comment by OoiSC** [comment]
I have checked my GeForce MX150 specs. The RAM is even smaller - only just 2GB. I am using a notebook PC and the MX150 is built-in.

Thanks for your advice on using Google Colab.

**Comment by faustomorales** [comment]
I'll close this issue for now but feel free to comment back to re-open if you find that there was more to this than the hardware limitation.
