### ISSUE TITLE
Prediction not running on GPU

### ISSUE THREAD

**Issue by vasanththangavel** [faustomorales/keras-ocr#44]
@faustomorales prediction always running on cpu ,Is there any option to change it to gpu or is there any minimum requirement for gpu, because i had only 2gb of Quadro K3000M.

**Comment by faustomorales** [comment]
Hi @vasanththangavel! Thanks for your question. The GPU configuration is determined by TensorFlow. You can see if TensorFlow sees the GPU using:

```python
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))
```

That should get you started with figuring out how to get the dependencies set up to use the GPU. That said, 2GB is probably not enough memory for the models in this package to run on the GPU (you will probably get out-of-memory errors). So it may not be worth figuring out. Let us know how it goes!

**Comment by vasanththangavel** [comment]
I tried this code
`import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))` but it returns empty list. so i tried different tensorflow version like 2.1.1 and 2.0.0 which is compatible for cuda 10.2 but still issue not resolved.

**Comment by faustomorales** [comment]
Configuring TensorFlow on GPU is a TensorFlow issue that, unfortunately, cannot be resolved by this package. Please see https://www.tensorflow.org/install/gpu for instructions. StackOverflow may have helpful information for troubleshooting TensorFlow / CUDA / GPU issues.
