### ISSUE TITLE
Unsupported depth of input image

### ISSUE THREAD

**Issue by Johndirr** [faustomorales/keras-ocr#5]
I just ran the example from: 
> https://keras-ocr.readthedocs.io/en/latest/examples/using_pretrained_models.html

with several png and jpg files and always got the following error:

> (keraspypi) retrohelix@retrohelix-P64-HJ-HK1:~/.virtualenvs/test$ python bla.py 
> Looking for /home/retrohelix/.keras-ocr/craft_mlt_25k.h5
> 2020-01-04 16:40:15.855346: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-01-04 16:40:15.877424: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
> 2020-01-04 16:40:15.878135: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3dfe2c0 executing computations on platform Host. Devices:
> 2020-01-04 16:40:15.878149: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
> WARNING:tensorflow:From /home/retrohelix/.virtualenvs/keraspypi/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py:5783: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
> Looking for /home/retrohelix/.keras-ocr/crnn_kurapan.h5
> Traceback (most recent call last):
>   File "bla.py", line 12, in <module>
>     predictions = pipeline.recognize(image=image)
>   File "/home/retrohelix/.virtualenvs/keraspypi/lib/python3.6/site-packages/keras_ocr/pipeline.py", line 49, in recognize
>     **recognition_kwargs)
>   File "/home/retrohelix/.virtualenvs/keraspypi/lib/python3.6/site-packages/keras_ocr/recognition.py", line 398, in recognize_from_boxes
>     [cv2.cvtColor(crop, cv2.COLOR_RGB2GRAY)[..., np.newaxis] for crop in crops])
>   File "/home/retrohelix/.virtualenvs/keraspypi/lib/python3.6/site-packages/keras_ocr/recognition.py", line 398, in <listcomp>
>     [cv2.cvtColor(crop, cv2.COLOR_RGB2GRAY)[..., np.newaxis] for crop in crops])
> cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::<unnamed>::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> > Unsupported depth of input image:
> >     'VDepth::contains(depth)'
> > where
> >     'depth' is 4 (CV_32S)

Any idea what I can do about this?

**Comment by faustomorales** [comment]
Thanks for reporting this! I had made a mistake that caused `keras_ocr.tools.warpBox` to return images as `int64` arrays instead of `uint8` arrays as required by OpenCV. It's fixed as of 2acb106f0f33aa37a83fc159df04a9c68d14e712 which also adds a unit test to make sure that example works in the future. I also published a fixed version to PyPi so you can get it using `pip install keras-ocr>=0.5.1`.

Let me know if this resolves the problem. Thanks!

**Comment by Johndirr** [comment]
Bingo! 
Thank you. I used `pip install --upgrade keras-ocr` to upgrade to the new version and tested again and at least the "unsupported depth error" is gone. But now I get his error:
> Successfully installed keras-ocr-0.5.1
> (keraspypi) retrohelix@retrohelix-P64-HJ-HK1:~/Programming/test$ python bla.py 
> Looking for /home/retrohelix/.keras-ocr/craft_mlt_25k.h5
> 2020-01-04 18:45:38.643560: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-01-04 18:45:38.675349: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
> 2020-01-04 18:45:38.676041: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4cf4c40 executing computations on platform Host. Devices:
> 2020-01-04 18:45:38.676086: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
> WARNING:tensorflow:From /home/retrohelix/.virtualenvs/keraspypi/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py:5783: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
> Looking for /home/retrohelix/.keras-ocr/crnn_kurapan.h5
> 2020-01-04 18:45:46.304798: W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries: Invalid argument: Functions '__inference_standard_lstm_5013' and '__inference_standard_lstm_5013_specialized_for_lstm_10_back_StatefulPartitionedCall_at___inference_keras_scratch_graph_8029' both implement 'lstm_fa72b496-e092-49d4-9523-2f51f2f55567' but their signatures do not match.

Tried uninstalling and reinstalling the newest version with `pip uninstall keras-ocr` but to no avail. Same outcome.

Shall I close this issue and open a new one?

**Comment by faustomorales** [comment]
I think we should be able to resolve quickly so no need for a separate issue yet. All of these look like typical TensorFlow warnings that come up depending on your hardware and how the TensorFlow distribution was compiled. Are you sure an exception was raised and that the `recognize` function didn't return results? If there is, in fact, an exception, I can try to reproduce if you let me know what the output of the following is:

```
import tensorflow as tf
print(tf.__version__)
```

This package works best with TensorFlow version >= 2.0.0.

**Comment by Johndirr** [comment]
Ok. It somehow works with the warning (text gets detected and recognized) but there is no image output. I tested by just printing the text in the example.
```
# Plot the results.
fig, ax = plt.subplots()
ax.imshow(keras_ocr.tools.drawBoxes(image, predictions, boxes_format='predictions'))
for text, box in predictions:
    ax.annotate(s=text, xy=box[0], xytext=box[0] - 50, arrowprops={'arrowstyle': '->'})
    print(text)
```

**Comment by faustomorales** [comment]
Ah, yes -- the example was tested in a Jupyter notebook where the image would appear in the cell output. You may have to add `plt.show()` at the end to get the figure to appear if you're running from the command line.

As for the warnings, they are just letting you know that TensorFlow could run faster if certain optimizations were made during compilation. It's a little noisy sometimes but they will only appear when you first start the session.

**Comment by Johndirr** [comment]
Oh, `plt.show()` is missing :D

**Comment by Johndirr** [comment]
Thank you very much for your help. I close this.

**Comment by faustomorales** [comment]
FYI, I've added `plt.show()` to the example code so others don't hit the same bump.
