### ISSUE TITLE
Question: Purpose of `rnn_steps_to_discard` in recognition

### ISSUE THREAD

**Issue by francotheengineer** [faustomorales/keras-ocr#52]
Hi!

Thanks for the good library. 

I'm looking at the code for the detector, namely the last Lamda function of the Recognition model.
https://github.com/faustomorales/keras-ocr/blob/master/keras_ocr/recognition.py#L285
`x = keras.layers.Lambda(lambda x: x[:, rnn_steps_to_discard:])(x)`

What is the purpose of the Lamda function that discards the first few steps of the RNN? I would have thought that all the RNN steps are needed - what are the advantages of ignoring them? 

Kind regards indeed, Franco

**Comment by faustomorales** [comment]
Hi @francotheengineer! Thank you for your great question.

The RNN steps directly correlate to vertical slices of the input image, which is a cropped word. The first few steps of the RNN contain character inferences based on very little information, as only a few slices of the input image are included. So we do not include them in inference. However, those steps are not exactly fully discarded. The output of step N affects the output of step N+1, and so on. So even though we do not care to use the character predictions from Step 1, the state of Step 1 was included in calculating Step 2, which was used in calculating Step 3, which we do use directly for inference. Removing the first couple steps is used in most examples for convolutional recurrent neural networks for OCR (e.g., see the `decode_batch` function in the [Keras OCR example](https://keras.io/examples/image_ocr/)).

Does that answer your question? I realize it lacks a robust theoretical underpinning (e.g., why discard two steps? Why not three?). But there's certainly no reason why you couldn't try using the model with `rnn_steps_to_discard=0` to see for yourself how this affects the quality of the recognition step.

**Comment by faustomorales** [comment]
Closing this issue as it is primarily a Q&A matter as opposed to a bug or feature request. If I'm mistaken, please do comment back and we can re-open. Thanks!

**Comment by francotheengineer** [comment]
Thanks so much for the detailed help! Thanks so much! Franco
