### ISSUE TITLE
Very slow detector inference speed

### ISSUE THREAD

**Issue by kymillev** [faustomorales/keras-ocr#55]
It seems the getBoxes method in the detector is very slow and the main bottleneck for good inference speeds. I was able to modify the detection part to work on batches using the tf.data.datasets API, which made the detection part quite fast. I used a batch size of 8 on a V100 GPU.

Time for detection (8660 images 1000x1000): **1032 s**
Time for getBoxes of those images: **11 729 s**

Any ideas how to improve the performance of the getBoxes step? I assume it is slow cause it has to process each result one at a time, get connectedcomponents and then process those one at a time.

I'm gonna try some things with Numba to speed up the loop over each connectedcomponent.

**Comment by faustomorales** [comment]
Yes, this is an area for development. One way to try to speed this up would be to move the calculation of connected components (along with the preprocessing steps) into the TensorFlow graph. `tensorflow-addons` appears to have [an implementation](https://www.tensorflow.org/addons/api_docs/python/tfa/image/connected_components). It might be quite a lift, though.

**Comment by kymillev** [comment]
I have found the problem, it had nothing to do with the source code, was a problem in my setup. I'm using a docker container on a shared virtual wall which has 96 CPUs, turns out OpenCV thought it could use all 96, while only 4 are allocated to me. By using cv2.setNumThreads(4), I was able to reduce code execution time on getBoxes by 20 times, which made it faster than the detection step.

**Comment by trungpham2606** [comment]
@kymillev @faustomorales 
Actually the time for feeding an image through detection network is large. It takes about 0.7s on my PC with Nvidia gtx 1060, The whole time on get_boxes function is 0.8s
