### ISSUE TITLE
Do keras OCR suited for scanned documents ?

### ISSUE THREAD

**Issue by Duv54** [faustomorales/keras-ocr#59]
HI,
I'm new to the universe of OCR and document analysis. So to discover that, I'm working on large documents like scanned invoices with a lot of noises. Do you think that using keras-ocr instead of tesseract would be possible on this type of data ? Or there are another tools build for OCR on these documents  exist ?

**Comment by faustomorales** [comment]
Hi @Duv54 -- I would recommend trying Tesseract and `keras-ocr` side-by-side and seeing which one better suits your needs.

**Comment by Duv54** [comment]
Thanks a lot for your response @faustomorales !

**Comment by faustomorales** [comment]
Closing this issue as I believe the original question was addressed. Please comment back if you disagree. Thanks!
