### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by suyashjoshi** [faustomorales/keras-ocr#6]
Hi,

When I run the program with my business card test image, getting this error 

`TypeError: resize_bilinear() got an unexpected keyword argument 'half_pixel_centers'`

What does it mean? What am I doing wrong? Are there any example programs I can try?

Thanks,
Suyash

![bus-card](https://user-images.githubusercontent.com/395039/71770765-80b5ad80-2ee5-11ea-836e-ec0792bd3be8.jpg)

**Comment by faustomorales** [comment]
Hi @suyashjoshi - It looks like you're using an older version of TensorFlow. If you upgrade to TensorFlow >= 2.0.0 with `pip install --upgrade tensorflow`, I believe it will likely resolve this issue.

For what it's worth, I ran the pipeline on your image using the following code and it did a decent job, I think.

```python
import matplotlib.pyplot as plt

import keras_ocr

# keras-ocr will automatically download pretrained
# weights for the detector and recognizer.
pipeline = keras_ocr.pipeline.Pipeline()

image = keras_ocr.tools.read('https://user-images.githubusercontent.com/395039/71770765-80b5ad80-2ee5-11ea-836e-ec0792bd3be8.jpg')

# Predictions is a list of (text, box) tuples.
predictions = pipeline.recognize(image=image)

# Plot the results.
fig, ax = plt.subplots(figsize=(15, 8))
ax.imshow(keras_ocr.tools.drawBoxes(image, predictions, boxes_format='predictions'))
for text, box in predictions:
    ax.annotate(s=text, xy=box[0], xytext=box[0] -50, arrowprops={'arrowstyle': '->'})
plt.show()
fig.tight_layout()
fig.savefig('example.jpg')
```

![example business card results](https://user-images.githubusercontent.com/9735401/71770838-99c75a00-2ef7-11ea-8393-3d0955dc5229.jpg)

**Comment by suyashjoshi** [comment]
Thank you so much, that worked. I'll write a blog about this library with a business card example :)
