### ISSUE TITLE
Box points order may not be correct after cropping

### ISSUE THREAD

**Issue by dsp05** [faustomorales/keras-ocr#60]
For text boxes with a large rotation around the Z-axis, the cropped text may have the wrong orientation.

<img width="367" alt="Screen Shot 2020-04-07 at 5 40 06 PM" src="https://user-images.githubusercontent.com/752718/78722489-988f3a00-78f7-11ea-8d8e-0a449d287f19.png">

**Comment by faustomorales** [comment]
This was closed by https://github.com/faustomorales/keras-ocr/pull/61 -- thanks for contributing the fix!
