### ISSUE TITLE
Memory-leak like behavior during long-term usage

### ISSUE THREAD

**Issue by Dobiasd** [faustomorales/keras-ocr#65]
While using `keras-ocr` in a (web-) microservice, I noticed, Kubernetes regularly restarts the deployed pods with reason `OOMKilled`. So I created a minimal example to reproduce the issue locally:

```python3
# memleak.py

import logging
import os

import psutil

# Disable GPU, use CPU only
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

import keras_ocr

import numpy as np

# The following can somewhat reduce, but not completely remove, memory-leak like effects.
# import tensorflow
# tensorflow.config.threading.set_inter_op_parallelism_threads(1)
# tensorflow.config.threading.set_intra_op_parallelism_threads(1)

detector = keras_ocr.detection.Detector()

# Suppress warnings about tf.function retracing.
# see: https://github.com/faustomorales/keras-ocr/issues/63#issuecomment-613782841
logging.getLogger('tensorflow').setLevel(logging.ERROR)

for count in range(1000):
    memory_usage_in_MiB = psutil.Process().memory_info().rss / (1024 * 1024)
    print(f'Memory usage after {count} image(s) (in MiB):',
          f'{memory_usage_in_MiB:.3f}',
          flush=True)
    image_shape = [*np.random.randint(128, 1024, (2,)).tolist(), 3]
    image = np.random.randint(0, 256, image_shape, dtype=np.uint8)
    detector.detect([image])
```

Output:

```
Memory usage after 0 image(s) (in MiB): 557.496
Memory usage after 1 image(s) (in MiB): 664.105
Memory usage after 2 image(s) (in MiB): 688.348
Memory usage after 3 image(s) (in MiB): 771.270
Memory usage after 4 image(s) (in MiB): 776.832
Memory usage after 5 image(s) (in MiB): 783.473
Memory usage after 6 image(s) (in MiB): 804.773
Memory usage after 7 image(s) (in MiB): 847.602
Memory usage after 8 image(s) (in MiB): 848.891
Memory usage after 9 image(s) (in MiB): 852.805
Memory usage after 10 image(s) (in MiB): 854.340
Memory usage after 11 image(s) (in MiB): 890.387
[...]
Memory usage after 99 image(s) (in MiB): 1646.906
Memory usage after 100 image(s) (in MiB): 1647.102
Memory usage after 101 image(s) (in MiB): 1647.055
[...]
Memory usage after 199 image(s) (in MiB): 2536.004
Memory usage after 200 image(s) (in MiB): 2563.195
Memory usage after 201 image(s) (in MiB): 2620.180
[...]
Memory usage after 399 image(s) (in MiB): 4365.938
Memory usage after 400 image(s) (in MiB): 4366.164
Memory usage after 401 image(s) (in MiB): 4366.125
[...]
...
```

The situation can also be created using Docker by running `docker build -t deleteme .` with the following `Dockerfile`:

```
FROM python:3.7

RUN pip install tensorflow==2.1.0 keras-ocr==0.8.3 psutil==5.7.0

# Disable the Docker cache from this stage on, see https://stackoverflow.com/a/58801213/1866775
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

ADD ./memleak.py /
RUN python /memleak.py
```

Maybe it has something to do with the images all having different shapes?

**Comment by Dobiasd** [comment]
[The memleak behavior can be reproduced in pure TensorFlow](https://github.com/tensorflow/tensorflow/issues/38598), i.e., without using `keras-ocr` at all. Thus `keras-ocr` probably is innocent. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
Interestingly, while downgrading TensorFlow to version `2.0.1` helps to avoid the memleak from the minimal example in [tensorflow/issues/38598](https://github.com/tensorflow/tensorflow/issues/38598), for some models, e.g., the detector model used in `keras-ocr`, to be free of memleak behavior, TensorFlow needs to be downgraded to `1.15.2`.

So, in summary, `keras-ocr` can run into this bug when using TensorFlow `2.0.0` or higher. `1.15.2` and lower is fine. Luckily, `keras-ocr` works with `1.15.2`, despite the [`README.md` stating](https://github.com/faustomorales/keras-ocr/blob/9dd79f345a453adeb196fba1e21d6d4bd1aac442/README.md#installation) it needs `TensorFlow >= 2.0.0`.

**Comment by faustomorales** [comment]
Really appreciate you finding this bug in TensorFlow and providing such a well-documented issue for them to investigate. As far as version support, good to know that inference works in 1.15. I'll admit that was a happy accident. When I set the requirement for TF 2.x, it was mostly so I wouldn't feel on the hook for testing everything on 1.x. It's lazy, I know. :/

**Comment by Dobiasd** [comment]
No worries, I fully empathize. There are more fun (and very likely more productive) things to do than meticulously testing different versions of all dependencies.

Also, I think requiring TF 2.0 is totally reasonable. It's been available long enough. :+1:

**Comment by Dobiasd** [comment]
Just tried with the latest `tf-nightly` (`tf-nightly==2.3.0.dev20200513`), and can happily confirm, the memleak [seems to be fixed](https://gist.github.com/Dobiasd/da5e045d69fac73fc53af462c5b6abf9)! :tada:

**Comment by Dobiasd** [comment]
For completeness: The memleak was [fixed in `tf-nightly`](https://github.com/tensorflow/tensorflow/issues/38598#issuecomment-628429472). So likely the next official release will also be fine.
