### ISSUE TITLE
keyword argument 'include_top' Does not exist.

### ISSUE THREAD

**Issue by nxgtrturbo** [faustomorales/keras-ocr#66]
I was trying to play with this, following the official tutorial [here](https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html).

However, when running:
`recognizer = keras_ocr.recognition.Recognizer(alphabet=recognizer_alphabet,weights='kurapan',include_top=False)`

I get:
`TypeError: __init__() got an unexpected keyword argument 'include_top'`

When checking the code [here](https://github.com/faustomorales/keras-ocr/blob/master/keras_ocr/recognition.py), I indeed see such parameter does not exist.

**Comment by faustomorales** [comment]
Great catch. This argument was removed because it is now inferred from the combination of `alphabet` and `weights`. I've just pushed f6ff3c3 which fixes this. Thanks again!
