### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by harshall28** [faustomorales/keras-ocr#7]
Hi, Can you please specify the versions of Python, Tensorflow and Keras compatible with this API?

**Comment by faustomorales** [comment]
Thanks for raising this. Yes, that would be helpful. I've added a note to the README and the documentation just now as part of https://github.com/faustomorales/keras-ocr/commit/6a1590f92867d45467ecfcf134f19b4cc50c3192. But, just to close the loop, this package supports Python >= 3.6 and TensorFlow >= 2.0.0. It uses `tf.keras` so a separate Keras installation is not necessary.
