### ISSUE TITLE
Return predictions to string, without ploting

### ISSUE THREAD

**Issue by andreluisos** [faustomorales/keras-ocr#72]
How can I return the predictions to a string? I don't need the plotting.

**Comment by shivam-kotwalia** [comment]
A very dirty and quick way to save text in file - 

`x_max = 0 
temp_str = ""
myfile = open("marnix_text.txt", "a+")
for i in prediction[0]:
    x_max_local = i[1][:, 0].max()

    if x_max_local > x_max:
        x_max = x_max_local
        temp_str = temp_str + " " + i[0].ljust(15)
    else:
        x_max = 0
        temp_str = temp_str + "\n"
        myfile.write(temp_str)
        print(temp_str)
        temp_str = ""
myfile.close()`

**Comment by faustomorales** [comment]
This appears to have been resolved. Thank you!
