### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by EkramulHoque** [faustomorales/keras-ocr#79]
Hello,
I have trying to download the detection model from craft, however its throwing me this error 'connection reset by peer'. It works in google colab but fails in my local machine. I am running
Ubuntu 16.04 with Python 3.7.6

Code:
detector = keras_ocr.detection.Detector()

Thanks

**Comment by threefoldo** [comment]
You have to manually download those files from mediafire, you can search "mediafire" in the code to get the url. I always use a VPN or SSR proxy.

**Comment by faustomorales** [comment]
Closing because this appears to be network related. We use MediaFire to host files because Google Cloud hosting was getting expensive. It sounds like they avoid serving direct downloads to VPNs and proxies.  As stated by @threefoldo (thanks!) you can also download the files manually.
