### ISSUE TITLE
How to get character-level prediction ?

### ISSUE THREAD

**Issue by trungpham2606** [faustomorales/keras-ocr#84]
@faustomorales 
Thank you for sharing such a great module.
But I wonder how to get character-level prediction instead of whole words ?
I tried to change some threshold parameters but it seems doesnt work.

**Comment by faustomorales** [comment]
I don't think this is possible with the CRAFT text detector -- at least not in an obvious and reliable way. This is not a bug, so I'm closing this issue for now.
