### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by harshall28** [faustomorales/keras-ocr#9]
Hi,

Thanks for this work.

Is there any way we can perform batch processing during inference instead of passing single image every time?

**Comment by faustomorales** [comment]
That's definitely part of the plan. You could do it directly with the `detector` (`detector.detect` allows you to pass multiple images to get text boxes for multiple images at the same time) and `recognizer`. That said, there are some known kinks to work out with the RNN layers in the recognizer that come up when conducting inference with larger batch sizes. Once that's fixed, I'd like to add a function to allow people to do inference across multiple images with batching in the `pipeline`.

My winter vacation is over so I can't contribute as frequently but watch this space!

**Comment by faustomorales** [comment]
This has been implemented as of 8de825e5a09d8efd3d98dbcab7501857fe956bb7 and is in v0.6.0. The README and examples have been updated accordingly. `pipeline.recognize` now takes lists of images instead of single images.

**Comment by faustomorales** [comment]
I think I've addressed this request as discussed above. If you find that it does not meet your needs, please comment on this issue and we can revisit. Thank you!
